name: Capture Screenshot

on:
  push:
    branches:
      - main

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install puppeteer

    - name: Capture Screenshot
      run: |
        const puppeteer = require('puppeteer');

        (async () => {
          const browser = await puppeteer.launch();
          const page = await browser.newPage();
          await page.goto('https://cloudirector.github.io');  // Replace with your actual website URL
          await page.screenshot({ path: 'screenshot.png' });
          await browser.close();
        })();

    - name: Commit Screenshot
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add screenshot.png
        git commit -m 'Add screenshot'
        git push
